# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\danie\OneDrive\Documents\IDS-GUI\IDS.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.settingsTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.settingsTabs.setGeometry(QtCore.QRect(0, 0, 801, 101))
        self.settingsTabs.setObjectName("settingsTabs")
        self.testTab = QtWidgets.QWidget()
        self.testTab.setObjectName("testTab")
        self.carTypeButton = QtWidgets.QPushButton(self.testTab)
        self.carTypeButton.setGeometry(QtCore.QRect(10, 10, 111, 23))
        self.carTypeButton.setObjectName("carTypeButton")
        self.canLogButton = QtWidgets.QPushButton(self.testTab)
        self.canLogButton.setGeometry(QtCore.QRect(10, 40, 111, 23))
        self.canLogButton.setObjectName("canLogButton")
        self.dnnModelButton = QtWidgets.QPushButton(self.testTab)
        self.dnnModelButton.setGeometry(QtCore.QRect(560, 10, 111, 23))
        self.dnnModelButton.setObjectName("dnnModelButton")
        self.canProbabilityButton = QtWidgets.QPushButton(self.testTab)
        self.canProbabilityButton.setGeometry(QtCore.QRect(560, 40, 111, 23))
        self.canProbabilityButton.setObjectName("canProbabilityButton")
        self.testTabLabel = QtWidgets.QLabel(self.testTab)
        self.testTabLabel.setGeometry(QtCore.QRect(330, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.testTabLabel.setFont(font)
        self.testTabLabel.setTextFormat(QtCore.Qt.AutoText)
        self.testTabLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testTabLabel.setObjectName("testTabLabel")
        self.beginTestButton = QtWidgets.QPushButton(self.testTab)
        self.beginTestButton.setGeometry(QtCore.QRect(410, 40, 91, 23))
        self.beginTestButton.setObjectName("beginTestButton")
        self.idsCheckBox = QtWidgets.QCheckBox(self.testTab)
        self.idsCheckBox.setGeometry(QtCore.QRect(320, 40, 70, 21))
        self.idsCheckBox.setObjectName("idsCheckBox")
        self.carTypeLabel = QtWidgets.QLabel(self.testTab)
        self.carTypeLabel.setGeometry(QtCore.QRect(130, 10, 131, 21))
        self.carTypeLabel.setObjectName("carTypeLabel")
        self.canLogLabel = QtWidgets.QLabel(self.testTab)
        self.canLogLabel.setGeometry(QtCore.QRect(130, 40, 131, 21))
        self.canLogLabel.setObjectName("canLogLabel")
        self.dnnModelLabel = QtWidgets.QLabel(self.testTab)
        self.dnnModelLabel.setGeometry(QtCore.QRect(680, 10, 131, 21))
        self.dnnModelLabel.setObjectName("dnnModelLabel")
        self.canProbabilityLabel = QtWidgets.QLabel(self.testTab)
        self.canProbabilityLabel.setGeometry(QtCore.QRect(680, 40, 131, 21))
        self.canProbabilityLabel.setObjectName("canProbabilityLabel")
        self.settingsTabs.addTab(self.testTab, "")
        self.trainTab = QtWidgets.QWidget()
        self.trainTab.setObjectName("trainTab")
        self.pushButton_13 = QtWidgets.QPushButton(self.trainTab)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 10, 81, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.trainingCanLogLabel = QtWidgets.QLabel(self.trainTab)
        self.trainingCanLogLabel.setGeometry(QtCore.QRect(100, 10, 141, 20))
        self.trainingCanLogLabel.setObjectName("trainingCanLogLabel")
        self.hiddenUnitsLabel = QtWidgets.QLabel(self.trainTab)
        self.hiddenUnitsLabel.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.hiddenUnitsLabel.setObjectName("hiddenUnitsLabel")
        self.hiddenUnitsLineEdit = QtWidgets.QLineEdit(self.trainTab)
        self.hiddenUnitsLineEdit.setGeometry(QtCore.QRect(100, 40, 113, 20))
        self.hiddenUnitsLineEdit.setObjectName("hiddenUnitsLineEdit")
        self.learningRateLabel = QtWidgets.QLabel(self.trainTab)
        self.learningRateLabel.setGeometry(QtCore.QRect(590, 10, 81, 20))
        self.learningRateLabel.setObjectName("learningRateLabel")
        self.learningRateLineEdit = QtWidgets.QLineEdit(self.trainTab)
        self.learningRateLineEdit.setGeometry(QtCore.QRect(680, 10, 113, 20))
        self.learningRateLineEdit.setObjectName("learningRateLineEdit")
        self.numStepsLineEdit = QtWidgets.QLineEdit(self.trainTab)
        self.numStepsLineEdit.setGeometry(QtCore.QRect(680, 40, 113, 20))
        self.numStepsLineEdit.setObjectName("numStepsLineEdit")
        self.numStepsLabel = QtWidgets.QLabel(self.trainTab)
        self.numStepsLabel.setGeometry(QtCore.QRect(590, 40, 81, 20))
        self.numStepsLabel.setObjectName("numStepsLabel")
        self.trainingLabel = QtWidgets.QLabel(self.trainTab)
        self.trainingLabel.setGeometry(QtCore.QRect(330, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.trainingLabel.setFont(font)
        self.trainingLabel.setTextFormat(QtCore.Qt.AutoText)
        self.trainingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trainingLabel.setObjectName("trainingLabel")
        self.batchSizeLabel = QtWidgets.QLabel(self.trainTab)
        self.batchSizeLabel.setGeometry(QtCore.QRect(310, 40, 81, 20))
        self.batchSizeLabel.setObjectName("batchSizeLabel")
        self.batchSizeLineEdit = QtWidgets.QLineEdit(self.trainTab)
        self.batchSizeLineEdit.setGeometry(QtCore.QRect(400, 40, 113, 20))
        self.batchSizeLineEdit.setObjectName("batchSizeLineEdit")
        self.settingsTabs.addTab(self.trainTab, "")
        self.attacksGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.attacksGroupBox.setGeometry(QtCore.QRect(650, 100, 151, 231))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.attacksGroupBox.setFont(font)
        self.attacksGroupBox.setObjectName("attacksGroupBox")
        self.randomCheckBox = QtWidgets.QCheckBox(self.attacksGroupBox)
        self.randomCheckBox.setGeometry(QtCore.QRect(10, 30, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.randomCheckBox.setFont(font)
        self.randomCheckBox.setObjectName("randomCheckBox")
        self.spoofingCheckBox = QtWidgets.QCheckBox(self.attacksGroupBox)
        self.spoofingCheckBox.setGeometry(QtCore.QRect(10, 50, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spoofingCheckBox.setFont(font)
        self.spoofingCheckBox.setObjectName("spoofingCheckBox")
        self.dosCheckBox = QtWidgets.QCheckBox(self.attacksGroupBox)
        self.dosCheckBox.setGeometry(QtCore.QRect(10, 70, 70, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dosCheckBox.setFont(font)
        self.dosCheckBox.setObjectName("dosCheckBox")
        self.randomButton = QtWidgets.QPushButton(self.attacksGroupBox)
        self.randomButton.setGeometry(QtCore.QRect(90, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.randomButton.setFont(font)
        self.randomButton.setObjectName("randomButton")
        self.spoofingButton = QtWidgets.QPushButton(self.attacksGroupBox)
        self.spoofingButton.setGeometry(QtCore.QRect(90, 50, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spoofingButton.setFont(font)
        self.spoofingButton.setObjectName("spoofingButton")
        self.dosButton = QtWidgets.QPushButton(self.attacksGroupBox)
        self.dosButton.setGeometry(QtCore.QRect(90, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dosButton.setFont(font)
        self.dosButton.setObjectName("dosButton")
        self.reportGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.reportGroupBox.setGeometry(QtCore.QRect(0, 100, 171, 471))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reportGroupBox.setFont(font)
        self.reportGroupBox.setObjectName("reportGroupBox")
        self.accuracyLabel = QtWidgets.QLabel(self.reportGroupBox)
        self.accuracyLabel.setGeometry(QtCore.QRect(10, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.accuracyLabel.setFont(font)
        self.accuracyLabel.setObjectName("accuracyLabel")
        self.correctLabel = QtWidgets.QLabel(self.reportGroupBox)
        self.correctLabel.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.correctLabel.setFont(font)
        self.correctLabel.setObjectName("correctLabel")
        self.maliciousCaughtLabel = QtWidgets.QLabel(self.reportGroupBox)
        self.maliciousCaughtLabel.setGeometry(QtCore.QRect(10, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maliciousCaughtLabel.setFont(font)
        self.maliciousCaughtLabel.setObjectName("maliciousCaughtLabel")
        self.falsePositiveLabel = QtWidgets.QLabel(self.reportGroupBox)
        self.falsePositiveLabel.setGeometry(QtCore.QRect(10, 100, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.falsePositiveLabel.setFont(font)
        self.falsePositiveLabel.setObjectName("falsePositiveLabel")
        self.messageLogCheckBox = QtWidgets.QCheckBox(self.reportGroupBox)
        self.messageLogCheckBox.setGeometry(QtCore.QRect(30, 410, 70, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.messageLogCheckBox.setFont(font)
        self.messageLogCheckBox.setText("")
        self.messageLogCheckBox.setObjectName("messageLogCheckBox")
        self.messageLogCheckBoxLabel = QtWidgets.QLabel(self.reportGroupBox)
        self.messageLogCheckBoxLabel.setGeometry(QtCore.QRect(50, 410, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.messageLogCheckBoxLabel.setFont(font)
        self.messageLogCheckBoxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLogCheckBoxLabel.setWordWrap(True)
        self.messageLogCheckBoxLabel.setObjectName("messageLogCheckBoxLabel")
        self.accuracyValue = QtWidgets.QLabel(self.reportGroupBox)
        self.accuracyValue.setGeometry(QtCore.QRect(120, 40, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.accuracyValue.setFont(font)
        self.accuracyValue.setObjectName("accuracyValue")
        self.correctValue = QtWidgets.QLabel(self.reportGroupBox)
        self.correctValue.setGeometry(QtCore.QRect(120, 60, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.correctValue.setFont(font)
        self.correctValue.setObjectName("correctValue")
        self.maliciousCaughtValue = QtWidgets.QLabel(self.reportGroupBox)
        self.maliciousCaughtValue.setGeometry(QtCore.QRect(120, 80, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.maliciousCaughtValue.setFont(font)
        self.maliciousCaughtValue.setObjectName("maliciousCaughtValue")
        self.falsePositiveValue = QtWidgets.QLabel(self.reportGroupBox)
        self.falsePositiveValue.setGeometry(QtCore.QRect(120, 100, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.falsePositiveValue.setFont(font)
        self.falsePositiveValue.setObjectName("falsePositiveValue")
        self.pushButton_12 = QtWidgets.QPushButton(self.reportGroupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(40, 440, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.timeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.timeGroupBox.setGeometry(QtCore.QRect(650, 330, 151, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.timeGroupBox.setFont(font)
        self.timeGroupBox.setObjectName("timeGroupBox")
        self.pushButton_15 = QtWidgets.QPushButton(self.timeGroupBox)
        self.pushButton_15.setGeometry(QtCore.QRect(40, 30, 61, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.timeGroupBox)
        self.pushButton_16.setGeometry(QtCore.QRect(0, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.timeGroupBox)
        self.pushButton_17.setGeometry(QtCore.QRect(70, 60, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.outputTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.outputTabs.setGeometry(QtCore.QRect(170, 419, 631, 151))
        self.outputTabs.setObjectName("outputTabs")
        self.outputTab = QtWidgets.QWidget()
        self.outputTab.setObjectName("outputTab")
        self.outputText = QtWidgets.QTextEdit(self.outputTab)
        self.outputText.setGeometry(QtCore.QRect(0, 0, 621, 121))
        self.outputText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.outputText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.outputText.setObjectName("outputText")
        self.outputTabs.addTab(self.outputTab, "")
        self.filterTab = QtWidgets.QWidget()
        self.filterTab.setObjectName("filterTab")
        self.falseNegativeCheckbox = QtWidgets.QCheckBox(self.filterTab)
        self.falseNegativeCheckbox.setGeometry(QtCore.QRect(20, 10, 91, 18))
        self.falseNegativeCheckbox.setObjectName("falseNegativeCheckbox")
        self.falsePositiveCheckBox = QtWidgets.QCheckBox(self.filterTab)
        self.falsePositiveCheckBox.setGeometry(QtCore.QRect(20, 30, 91, 18))
        self.falsePositiveCheckBox.setObjectName("falsePositiveCheckBox")
        self.truePositiveCheckBox = QtWidgets.QCheckBox(self.filterTab)
        self.truePositiveCheckBox.setGeometry(QtCore.QRect(20, 50, 91, 18))
        self.truePositiveCheckBox.setObjectName("truePositiveCheckBox")
        self.trueNegativeCheckBox = QtWidgets.QCheckBox(self.filterTab)
        self.trueNegativeCheckBox.setGeometry(QtCore.QRect(20, 70, 91, 18))
        self.trueNegativeCheckBox.setObjectName("trueNegativeCheckBox")
        self.benignCheckbox = QtWidgets.QCheckBox(self.filterTab)
        self.benignCheckbox.setGeometry(QtCore.QRect(130, 10, 91, 18))
        self.benignCheckbox.setObjectName("benignCheckbox")
        self.randomCheckbox = QtWidgets.QCheckBox(self.filterTab)
        self.randomCheckbox.setGeometry(QtCore.QRect(130, 30, 91, 18))
        self.randomCheckbox.setObjectName("randomCheckbox")
        self.spoofingCheckbox = QtWidgets.QCheckBox(self.filterTab)
        self.spoofingCheckbox.setGeometry(QtCore.QRect(130, 50, 91, 18))
        self.spoofingCheckbox.setObjectName("spoofingCheckbox")
        self.dosCheckbox = QtWidgets.QCheckBox(self.filterTab)
        self.dosCheckbox.setGeometry(QtCore.QRect(130, 70, 91, 18))
        self.dosCheckbox.setObjectName("dosCheckbox")
        self.outputTabs.addTab(self.filterTab, "")
        self.fakeOutputLabel = QtWidgets.QLabel(self.centralwidget)
        self.fakeOutputLabel.setGeometry(QtCore.QRect(270, 110, 301, 311))
        self.fakeOutputLabel.setText("")
        self.fakeOutputLabel.setPixmap(QtGui.QPixmap("FakeOutput.png"))
        self.fakeOutputLabel.setScaledContents(True)
        self.fakeOutputLabel.setObjectName("fakeOutputLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.settingsTabs.setCurrentIndex(1)
        self.outputTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.carTypeButton.setText(_translate("MainWindow", "Load Car Type"))
        self.canLogButton.setText(_translate("MainWindow", "Load CAN Log"))
        self.dnnModelButton.setText(_translate("MainWindow", "Load DNN Model"))
        self.canProbabilityButton.setText(_translate("MainWindow", "Load CAN Probability"))
        self.testTabLabel.setText(_translate("MainWindow", "Test Setup"))
        self.beginTestButton.setText(_translate("MainWindow", "Begin Test"))
        self.idsCheckBox.setText(_translate("MainWindow", "Use IDS"))
        self.carTypeLabel.setText(_translate("MainWindow", "Car Type File"))
        self.canLogLabel.setText(_translate("MainWindow", "CAN Log File"))
        self.dnnModelLabel.setText(_translate("MainWindow", "DNN Model File"))
        self.canProbabilityLabel.setText(_translate("MainWindow", "CAN Probability File"))
        self.settingsTabs.setTabText(self.settingsTabs.indexOf(self.testTab), _translate("MainWindow", "Test"))
        self.pushButton_13.setText(_translate("MainWindow", "Load CAN Log"))
        self.trainingCanLogLabel.setText(_translate("MainWindow", "CAN Log File"))
        self.hiddenUnitsLabel.setText(_translate("MainWindow", "Hidden Units:"))
        self.hiddenUnitsLineEdit.setText(_translate("MainWindow", "10, 20, 20, 20"))
        self.learningRateLabel.setText(_translate("MainWindow", "Learning Rate:"))
        self.learningRateLineEdit.setText(_translate("MainWindow", "0.1"))
        self.numStepsLineEdit.setText(_translate("MainWindow", "2000"))
        self.numStepsLabel.setText(_translate("MainWindow", "Num Steps:"))
        self.trainingLabel.setText(_translate("MainWindow", "Training"))
        self.batchSizeLabel.setText(_translate("MainWindow", "Batch Size:"))
        self.batchSizeLineEdit.setText(_translate("MainWindow", "750"))
        self.settingsTabs.setTabText(self.settingsTabs.indexOf(self.trainTab), _translate("MainWindow", "Train"))
        self.attacksGroupBox.setTitle(_translate("MainWindow", "Attacks"))
        self.randomCheckBox.setText(_translate("MainWindow", "Random"))
        self.spoofingCheckBox.setText(_translate("MainWindow", "Spoofing"))
        self.dosCheckBox.setText(_translate("MainWindow", "DOS"))
        self.randomButton.setText(_translate("MainWindow", "Manual"))
        self.spoofingButton.setText(_translate("MainWindow", "Manual"))
        self.dosButton.setText(_translate("MainWindow", "Manual"))
        self.reportGroupBox.setTitle(_translate("MainWindow", "Report"))
        self.accuracyLabel.setText(_translate("MainWindow", "Accuracy:"))
        self.correctLabel.setText(_translate("MainWindow", "Correct:"))
        self.maliciousCaughtLabel.setText(_translate("MainWindow", "Malicious Caught:"))
        self.falsePositiveLabel.setText(_translate("MainWindow", "False Positive:"))
        self.messageLogCheckBoxLabel.setText(_translate("MainWindow", "Include Message log with save"))
        self.accuracyValue.setText(_translate("MainWindow", "Val"))
        self.correctValue.setText(_translate("MainWindow", "Val"))
        self.maliciousCaughtValue.setText(_translate("MainWindow", "Val"))
        self.falsePositiveValue.setText(_translate("MainWindow", "Val"))
        self.pushButton_12.setText(_translate("MainWindow", "Save"))
        self.timeGroupBox.setTitle(_translate("MainWindow", "Time"))
        self.pushButton_15.setText(_translate("MainWindow", "Pause"))
        self.pushButton_16.setText(_translate("MainWindow", "<"))
        self.pushButton_17.setText(_translate("MainWindow", ">"))
        self.outputTabs.setTabText(self.outputTabs.indexOf(self.outputTab), _translate("MainWindow", "Output"))
        self.falseNegativeCheckbox.setText(_translate("MainWindow", "False Negative"))
        self.falsePositiveCheckBox.setText(_translate("MainWindow", "False Positive"))
        self.truePositiveCheckBox.setText(_translate("MainWindow", "True Positive"))
        self.trueNegativeCheckBox.setText(_translate("MainWindow", "True Negative"))
        self.benignCheckbox.setText(_translate("MainWindow", "Benign"))
        self.randomCheckbox.setText(_translate("MainWindow", "Random"))
        self.spoofingCheckbox.setText(_translate("MainWindow", "Spoofing"))
        self.dosCheckbox.setText(_translate("MainWindow", "DOS"))
        self.outputTabs.setTabText(self.outputTabs.indexOf(self.filterTab), _translate("MainWindow", "Filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

